import { StyleSheet } from 'react-native';
import { dark } from './dark';
import { light } from './light';

export type Palette = typeof light;
export const palette = (mode: 'light' | 'dark'): Palette => mode === 'dark' ? dark : light;

export const stylesFor = (c: Palette) => StyleSheet.create({
  screen: { flex: 1, backgroundColor: c.background },
  scroll: { flexGrow: 1, paddingHorizontal: 20, paddingTop: 24, paddingBottom: 28, alignItems: 'center', justifyContent: 'center' },
  content: { width: '100%', maxWidth: 1120 },
  top: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 28 },
  brand: { color: c.text, fontSize: 23, fontWeight: '800', letterSpacing: -0.9 },
  brandDot: { color: c.accent },
  themeButton: { width: 44, height: 44, alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: c.border, borderRadius: 22, backgroundColor: c.surface },
  authLayout: { width: '100%', alignSelf: 'center' },
  hero: { backgroundColor: c.hero, borderRadius: 22, padding: 36, justifyContent: 'space-between', minHeight: 520 },
  heroMark: { color: c.heroMuted, fontSize: 13, fontWeight: '700', letterSpacing: 1.1 },
  heroTitle: { color: c.heroText, fontSize: 46, lineHeight: 51, fontWeight: '800', letterSpacing: -2, maxWidth: 380 },
  heroBody: { color: c.heroMuted, fontSize: 16, lineHeight: 25, marginTop: 20, maxWidth: 360 },
  heroRule: { height: 1, backgroundColor: c.heroLine, marginBottom: 20 },
  heroFoot: { color: c.heroMuted, fontSize: 13, lineHeight: 20 },
  panel: { backgroundColor: c.surface, borderRadius: 22, padding: 34, borderWidth: 1, borderColor: c.border },
  heading: { color: c.text, fontSize: 34, lineHeight: 39, fontWeight: '800', letterSpacing: -1.2, marginBottom: 8 },
  loginHeading: { fontSize: 28, lineHeight: 34, letterSpacing: -0.7 },
  intro: { color: c.muted, fontSize: 15, lineHeight: 23, marginBottom: 26 },
  label: { color: c.text, fontWeight: '700', marginBottom: 8, fontSize: 13 },
  input: { backgroundColor: c.input, borderWidth: 1, borderColor: c.border, borderRadius: 11, paddingHorizontal: 15, paddingVertical: 12, color: c.text, fontSize: 16, minHeight: 52 },
  inputError: { borderColor: c.error, borderWidth: 2 },
  field: { marginBottom: 18 },
  error: { color: c.error, fontSize: 13, lineHeight: 18, marginTop: 6 },
  banner: { color: c.error, backgroundColor: c.errorSoft, padding: 13, borderRadius: 11, marginBottom: 16, lineHeight: 20 },
  success: { color: c.text, backgroundColor: c.soft, padding: 13, borderRadius: 11, marginBottom: 16, lineHeight: 20 },
  button: { backgroundColor: c.accent, borderRadius: 11, minHeight: 52, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 16, marginTop: 4 },
  buttonText: { color: c.accentText, fontSize: 15, fontWeight: '800' },
  buttonDisabled: { backgroundColor: c.soft },
  secondaryButton: { borderColor: c.border, borderWidth: 1, backgroundColor: c.surface },
  secondaryText: { color: c.text, fontWeight: '700', fontSize: 15 },
  textButton: { minHeight: 44, justifyContent: 'center', alignSelf: 'flex-start', paddingVertical: 8 },
  textButtonText: { color: c.accent, fontWeight: '700', fontSize: 14 },
  divider: { height: 1, backgroundColor: c.line, marginVertical: 23 },
  dividerLabel: { color: c.muted, fontSize: 13, textAlign: 'center', marginBottom: 14 },
  providerRow: { flexDirection: 'row', gap: 9 },
  providerButton: { flex: 1, minHeight: 76, borderWidth: 1, borderColor: c.border, borderRadius: 11, backgroundColor: c.input, alignItems: 'center', justifyContent: 'center', gap: 7, paddingHorizontal: 5 },
  providerText: { color: c.text, fontWeight: '700', fontSize: 12 },
  linkedProviderRow: { flexDirection: 'row', gap: 9, marginTop: 2 },
  linkedProvider: { flex: 1, minHeight: 82, borderWidth: 1, borderColor: c.border, borderRadius: 11, backgroundColor: c.input, alignItems: 'center', justifyContent: 'center', gap: 5, padding: 6 },
  linkedProviderActive: { borderColor: c.accent, backgroundColor: c.soft },
  linkedProviderName: { color: c.text, fontSize: 12, fontWeight: '700' },
  linkedProviderState: { color: c.muted, fontSize: 11, fontWeight: '600' },
  accountRow: { flexDirection: 'row', alignItems: 'center', flexWrap: 'wrap', marginTop: 14 },
  accountPrompt: { color: c.muted, fontSize: 14, marginRight: 6 },
  helpLinks: { flexDirection: 'row', flexWrap: 'wrap', columnGap: 20, marginTop: 3 },
  helpTitle: { color: c.muted, fontSize: 13, fontWeight: '700', marginBottom: 1 },
  chipRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 7, marginBottom: 10 },
  chip: { borderWidth: 1, borderColor: c.border, borderRadius: 9, padding: 10, backgroundColor: c.input },
  chipSelected: { backgroundColor: c.soft, borderColor: c.accent },
  chipText: { color: c.text, fontSize: 13, lineHeight: 18 },
  smallTitle: { color: c.text, fontSize: 17, fontWeight: '800', marginBottom: 13 },
  detail: { color: c.muted, fontSize: 14, lineHeight: 23 },
  detailStrong: { color: c.text, fontWeight: '700' },
  footer: { color: c.muted, textAlign: 'center', fontSize: 12, marginTop: 25, lineHeight: 18 }
});
